name: Deploy changes

on:
  workflow_call:
    inputs:
      forced_deployment:
        description: Deploy all resources in the cloud
        required: true
        type: boolean
  push: 
    branches: 
      - main
      - 'feature/**'
      - 'release/**'
      - develop     


jobs:
  parameters:
    name: Set parameters
    runs-on: python-runner
    outputs:
      ENVIRONMENT: ${{ steps.set_environment.outputs.ENVIRONMENT }}
      FORCED_DEPLOYMENT: ${{ inputs.forced_deployment || false }}
      FLAVOR_FOLDER: ${{ steps.set_version_folder.outputs.FLAVOR_FOLDER }}
    permissions:
      contents: write
    steps:
      - name: Set environment
        id: set_environment
        run: |
          case ${{ github.ref_name }} in
            develop)
              ENVIRONMENT=DEV
              ;;
            "feature"*)
              ENVIRONMENT=DEV
              ;;              
            "release"*)
              ENVIRONMENT=PRE
              ;;
            main)
              ENVIRONMENT=PRO
              ;;
          esac
          echo "The environment is: $ENVIRONMENT"
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
      - name: Set version folder
        id: set_version_folder
        run: |
          case ${{ github.ref_name }} in
            develop)
              FLAVOR_FOLDER=develop
              ;;
            "feature"*)
              FLAVOR_FOLDER=${{ github.ref_name }}
              ;;              
            "release"*)
              FLAVOR_FOLDER=release_candidate/${{ github.ref_name }}
              ;;
            main)
              FLAVOR_FOLDER=last
              VERSION_FOLDER=version/${{ github.ref_name }}
              ;;
          esac
          echo "last folder is: $FLAVOR_FOLDER"
          echo "FLAVOR_FOLDER=$FLAVOR_FOLDER" >> $GITHUB_OUTPUT

  fortify:
    name: Fortify
    needs: [parameters]
    uses: santander-group-shared-assets/gln-detect-asm-ssdlc-workflows/.github/workflows/sast-fortify.yml@v4.2.0
    if: ${{ needs.parameters.outputs.forced_deployment == false }}
    with:
      runs-on: python-runner
      timeout-minutes: 30
      tools_and_versions: >
        python:3.10.11
      ssc_url: "https://ssc.santander.fortifyhosted.com"
      sc_controller_url: "https://scsastctrl.santander.fortifyhosted.com/scancentral-ctrl"
      component: santander-group-wealth-ng_aih-dataplatform-python-data_framework
      version: 1
      build_tool: "none"
      criteria: "High"
    secrets:
      fortify_client_auth_token_hosted: ${{ secrets.FORTIFY_CLIENT_AUTH_TOKEN_HOSTED }}
      fortify_user: ${{ secrets.FORTIFY_USER }}
      fortify_password: ${{ secrets.FORTIFY_PASSWORD }}

  sonar:
    name: Sonar
    needs: [parameters]
    if: ${{ needs.parameters.outputs.forced_deployment == false }}
    runs-on: python-runner
    environment: ${{ needs.parameters.outputs.ENVIRONMENT }}
    steps:
      - name: Clone original repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}

      - name: SonarQube Scan
        uses: santander-group-wealth-ng/wmi-dataplatform-cicd-dataflow/.github/actions/code-analyze-sonar_qube_scan@main
        with:
              sonar-url: https://sonar-com.sgtech.gs.corp
              sonar-token: ${{ secrets.SGT79_SONAR_PRO_TOKEN }}
              sonar-project-key: wel:wel:aih-gdp:${{ needs.parameters.outputs.DATAFLOW }}
              sonar-project-version: ${{ vars.DATAFLOW_VERSION }}


  aws-s3-upload-all_environments:
    needs: [ parameters ]
    strategy:
      matrix:
        environment: [dev ,pre ,pro]
    uses: santander-group-wealth-ng/aih-dataplatform-python-data_framework/.github/workflows/upload.yml@feature/lxml
    secrets: inherit
    with:
      runner: python-runner
      environment:  ${{ matrix.environment }}
      flavor_folder: ${{ needs.parameters.outputs.FLAVOR_FOLDER }}




