name: Forced deploy to DEV

on:
  workflow_dispatch:
    inputs:
      data-catalog:
        description: Deploy data-catalog component
        type: boolean
        default: false
      orchertration:
        description: Deploy orchertration component
        type: boolean
        default: false
      transformation:
        description: Deploy transformation component
        type: boolean
        default: false
       

jobs:
  deploy: 
    name: This job is launched by ${{ github.ref_name }}
    uses: santander-group-wealth-ng/wmi-dataplatform-cicd-dataflow/.github/workflows/forced_deploy.yml@develop
    secrets: inherit
    if: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
    with:
      runner: python-runner
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      data-catalog: ${{ inputs.data-catalog }}
      orchertration: ${{ inputs.orchertration }}
      transformation: ${{ inputs.transformation }}
